#!/bin/bash
set -eu

if [ ! -d "/home/celestia/.celestia-light" ]; then
    celestia-da light init \
        --p2p.network $CELESTIA_P2P_NETWORK \
        --node.store /home/celestia/.celestia-light
fi

exec celestia-da light start \
    --p2p.network=$CELESTIA_P2P_NETWORK \
    --da.grpc.namespace=$CELESTIA_NAMESPACE \
    --da.grpc.listen=0.0.0.0:26650 \
    --core.ip $CELESTIA_CORE_IP \
    --node.store /home/celestia/.celestia-light \
    --gateway\
    --gateway.addr=0.0.0.0
